### ISSUE TITLE
No config file generating

### ISSUE THREAD

**Issue by MikeyProHD** [BigBoss320/Auto-CONFIG.JSON-for-SSBU#1]
When I clicked on AutoConfigUiBeta2, I clicked on the extra slot option (c08) and I selected my folder (I did a Shadow mod over Sonic) and clicked generate, but no config file appeared.

**Comment by BigBoss320** [comment]
Is there some message before, or really nothing happened when clicking on generate?

**Comment by BigBoss320** [comment]
I think you have the same issue as everyone in GameBanana. The app only work if you already have a config.json. Can you try it by creating a .json file in the folder please ? Else i just updated it. Try using the vBeta2.1

**Comment by MikeyProHD** [comment]
Sorry for the late reply! Your update worked flawlessly!

**Comment by BigBoss320** [comment]
Nice to hear it! Thx
