### ISSUE TITLE
Not able to add extra slot

### ISSUE THREAD

**Issue by kln581** [BigBoss320/Auto-CONFIG.JSON-for-SSBU#2]
[White-Red Wolf c08.zip](https://github.com/BigBoss320/Auto-CONFIG.JSON-for-SSBU/files/9639476/White-Red.Wolf.c08.zip)

**Comment by BigBoss320** [comment]
There's missing many files for the extra slots. Extra slots NEED all files that are required for a character that means : you have to extract ALL models of Wolf, their Textures, all motions and all Sounds/Voice of him. Here is the structure : 

For Wolf for example:
1) [ModName]
    - fighter
       - wolf
         - model
            - blaster
               - c08
                  - [all model/texture files]
             - body
               - c08
                  - [all model/texture files]
             - reticle
               - c08
                  - [all model/texture files]
             - wolfen
                - c08
                   - [all model/texture files]
          - motion
             - blaster
               - c08
                  - [all motion files]
             - blaster_bullet
               - c08
                 - [all motion files]
             - body
                - c08
                   - [all motion files]
             - illusion
                - c08
                   - [all motion files]
             - reticle
               - c08
                  - [all motion files]
             - wolfen
                - c08
                   - [all motion files]
   - sound
     - bank
        - fighter_voice (6 files)
           - vc_wolf_cheer_c08.[nu3audio/nus3bank/tonelabel]
           - vc_wolf_c08.[nu3audio/nus3bank/tonelabel]
        - fighter (3 files)
          - se_wolf_c08.[nu3audio/nus3bank/tonelabel]
   - ui (and all the ui that comes with it)

You also have to edit manually the ui_chara_db.prc located at "ui>param>database" to add a slot, and put it to the mod.

**Comment by BigBoss320** [comment]
I can make the mod complete to make it working

**Comment by kln581** [comment]
yes please

**Comment by kln581** [comment]
im not sure where to get those files tbh, or a program that can fetch them for me

**Comment by BigBoss320** [comment]
There is a program called "Arc Explorer" that can walk throught the files of the game and extract them but you need to have the ROM on you computer

**Comment by kln581** [comment]
how do you get the arc files from the nsp?

**Comment by BigBoss320** [comment]
> how do you get the arc files from the nsp?

The game file has to be converted to th data.arc, I don't know how to do it without using one the switch emulator (yuzu/Ryujinx)

**Comment by kln581** [comment]
i am using ryujinx

**Comment by kln581** [comment]
do you dump?

**Comment by BigBoss320** [comment]
Okay, do you have the last update of the game (13.0.1)?

**Comment by BigBoss320** [comment]
On Ryujinx, you just have to right click, extract data, RomFS

**Comment by BigBoss320** [comment]
It will take time

**Comment by BigBoss320** [comment]
Here is a working version on my switch but it is probable that it is not working on yours 
[White-Red Wolf c08.zip](https://github.com/BigBoss320/Auto-CONFIG.JSON-for-SSBU/files/9639712/White-Red.Wolf.c08.zip)
 and i don't know why but extra slots doesn't work on the emulator anymore

**Comment by kln581** [comment]
yeah doesnt work on emu

**Comment by BigBoss320** [comment]
That's weird because it works before but now it keeps crashing. Maybe due to one of it's update

**Comment by BigBoss320** [comment]
I found out the problem. it was the ui_chara_db.prcx
Replace the file by this one :
[ui_chara_db.zip](https://github.com/BigBoss320/Auto-CONFIG.JSON-for-SSBU/files/9640353/ui_chara_db.zip)

**Comment by BigBoss320** [comment]
Is it working now?

**Comment by BigBoss320** [comment]
I am closing this.
